version: '3'
#
#  Component arrangement is as below:
#  
#  ┌────────────┐    ┌────────────┐   ┌─────────────┐    ┌──────────┐
#  │            │    │            │   │             │    │          │
#  │ Simulator  ├───►│ Simulator  ├──►│  Mojaloop   ├───►│  Switch  │
#  │ Backend    │    │   Core     │   │  Connector  │    │          │
#  │            │◄───┤ Connector  │◄──┤             │◄───┤          │
#  └────────────┘    └────────────┘   └─────────────┘    └──────────┘
#  
# For this file to work with docker-compose up both the op-premise-deploy and ml-testing-toolkit repositories should be available locally in the same folder
# See https://github.com/pm4ml/on-premise-deploy
# And https://github.com/mojaloop/ml-testing-toolkit
#

services:

  mojaloop-testing-toolkit:
    image: mojaloop/ml-testing-toolkit:v12.4.1
    volumes:
      - "../../ml-testing-toolkit/spec_files:/opt/mojaloop-testing-toolkit/spec_files"
      - "../../ml-testing-toolkit/secrets:/opt/mojaloop-testing-toolkit/secrets"
    ports:
      - "5000:5000"
      - "5050:5050"
    command:
      - sh
      - -c
      - "npm start"

  mojaloop-testing-toolkit-ui:
    image: mojaloop/ml-testing-toolkit-ui:v12.2.2
    ports:
      - "6060:6060"
    environment:
      - API_BASE_URL=http://localhost:5050
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh

  keycloak:
    image: jboss/keycloak:12.0.4
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
      - KEYCLOAK_IMPORT=/tmp/pm4ml-realm.json
    volumes:
      - ./keycloak-realm.json:/tmp/pm4ml-realm.json
    ports:
      - "8080:8080"

  management-api:
    image: pm4ml/mojaloop-payment-manager-management-api:2.0.0
    environment:
      - AUTH_ENABLED=true
      - AUTH_PASS=pm4mltest123
      - AUTH_USER=pm4mltest
      - CACHE_HOST=redis
      - CACHE_SYNC_INTERVAL_SECONDS=10
      - DFSP_CA_PATH=/secrets
      - DFSP_CA_PATH=/tlsServerCA.pem
      # - DFSP_CLIENT_CSR_PARAMETERS=/resources/tlsClientCSRParameters.json
      - DFSP_CSR_KEY=a
      - DFSP_ID=datavision
      # - DFSP_SERVER_CSR_PARAMETERS=/resources/tlsServerCSRParameters.json
      - ENV_ID=1
      # Variable missing
      - MCM_API_TOKEN=
      - MCM_CLIENT_REFRESH_INTERVAL=300
      - MCM_CLIENT_SECRETS_LOCATION=/secrets
      # Variable missing
      - MCM_SERVER_ENDPOINT=
      - P12_PASS_PHRASE=SOME_S3C4R3_P@SS
      - PK_SECRETS_LOCATION=/secrets
      - PRIVATE_KEY_ALGORITHM=rsa
      - PRIVATE_KEY_LENGTH=4096
      - TLS_SERVER_PRIVATE_KEY=/tlsServerPvtKey.key
      - TLS_SERVER_PRIVATE_KEY=a
      - WS_PORT=4003
      - WS_URL=mojaloop-connector
      - dfspCsrPrivateKeyAlgorithm=rsa
      - dfspCsrPrivateKeyLength=4096
      - p12PassPhrase=SOME_S3C4R3_P@SS
      - tlsClientCSRParametersPath=/resources/tlsClientCSRParameters.json
      - tlsServerCAPath=/tlsServerCA.pem
      - tlsServerCSRParametersPath=/resources/tlsServerCSRParameters.json
      - tlsServerPvtKeyPath=/tlsServerPvtKey.key
    volumes:
      - "/tmp/secrets:/secrets"
    depends_on:
      - redis
      - keycloak
      - mojaloop-connector

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /prometheus.yml:/etc/prometheus/prometheus.yml

  simulator-core-connector:
    image: pm4ml/mojaloop-payment-manager-simulator-core-connector:1.4.2
    environment:
      - BACKEND_ENDPOINT=http://sim-backend:3002
      - MLCONN_OUTBOUND_ENDPOINT=http://mojaloop-connector:4001
    depends_on:
      - mojaloop-connector
      - sim-backend

  sim-backend:
    image: mojaloop/mojaloop-simulator
    environment:
      - CA_CERT_PATH=./secrets/cacert.pem
      #Institution ID maybe need to be numeric not sure
      - DFSP_ID=datavision
      - FEE_MULTIPLIER=0.0
      - HTTPS_ENABLED=false
      - LOG_INDENT=0
      - MODEL_DATABASE=./model.sqlite
      - MUTUAL_TLS_ENABLED=false
      - OUTBOUND_ENDPOINT=http://simulator-core-connector:3003
      - REPORT_API_LISTEN_PORT=3002
      # - RULES_FILE=../rules/rules.json
      - SERVER_CERT_PATH=./secrets/servercert.pem
      - SERVER_KEY_PATH=./secrets/serverkey.pem
      - SIMULATOR_API_LISTEN_PORT=3000
      - SQLITE_LOG_FILE=./log.sqlite
      - TEST_API_LISTEN_PORT=3003
    ports:
      - "3003:3003"

  redis:
    image: redis:6.2.4-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT=6379
      - REDIS_REPLICATION_MODE=master
      - REDIS_TLS_ENABLED=no

  mojaloop-connector:
    image: pm4ml/mojaloop-connector:13.2.0
    environment:
      - AUTO_ACCEPT_PARTY=true
      - AUTO_ACCEPT_QUOTES=true
      - BACKEND_ENDPOINT=simulator-core-connector:3000
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - DFSP_ID=datavision
      - ENABLE_TEST_FEATURES=true
      - INBOUND_LISTEN_PORT=4000
      - INBOUND_MUTUAL_TLS_ENABLED=false
      - IN_CA_CERT_PATH=/secrets/inbound-cacert.pem
      - IN_SERVER_CERT_PATH=/secrets/inbound-cert.pem
      - IN_SERVER_KEY_PATH=/secrets/inbound-key.pem
      - JWS_SIGN=false
      - JWS_SIGNING_KEY_PATH=/jwsSigningKey.key
      - JWS_VERIFICATION_KEYS_DIRECTORY=/jwsVerificationKeys
      - METRICS_SERVER_LISTEN_PORT=4004
      - MULTIPLE_PARTIES_RESPONSE=false
      - MGMT_API_WS_URL=management-api
      - OUTBOUND_LISTEN_PORT=4001
      - OUTBOUND_MUTUAL_TLS_ENABLED=false
      - OUT_CA_CERT_PATH=/secrets/outbound-cacert.pem
      - OUT_CLIENT_CERT_PATH=/secrets/outbound-cert.pem
      - OUT_CLIENT_KEY_PATH=/secrets/outbound-key.pem
      - PEER_ENDPOINT=mojaloop-testing-toolkit:5000
      - TEST_CA_CERT_PATH=/secrets/test-cacert.pem
      - TEST_CLIENT_CERT_PATH=/secrets/test-cert.pem
      - TEST_CLIENT_KEY_PATH=/secrets/test-key.pem
      - TEST_LISTEN_PORT=4002
      - TEST_MUTUAL_TLS_ENABLED=false
      - WS_PORT=4003
    volumes:
      - ./outbound-cacert.pem:/secrets/outbound-cacert.pem
      - ./outbound-cert.pem:/secrets/outbound-cert.pem
      - ./outbound-key.pem:/secrets/outbound-key.pem
      - ./inbound-cacert.pem:/secrets/inbound-cacert.pem
      - ./inbound-cert.pem:/secrets/inbound-cert.pem
      - ./inbound-key.pem:/secrets/inbound-key.pem
    depends_on:
      - redis
      - mojaloop-testing-toolkit

networks:
  default:
    name: mojaloop-testing-toolkit
      
